#!/usr/bin/env -S uv run --script
# /// script
# dependencies = [
#   "lxml",
# ]
# ///

# Python Standard Library
import subprocess
from pathlib import Path

# Third-Party Libraries
from lxml import etree


def run(cmd: list[str]) -> None:
    subprocess.run(cmd, check=True)


def build(lean_file: str) -> None:
    src = Path(lean_file)
    md = src.with_suffix(".lean.md")
    html = src.with_suffix(".lean.html")

    run(["mol", str(src)])  # -> .lean.md

    run(
        [
            "pandoc",
            "--standalone",
            "--toc",
            "--css=index.css",
            "--syntax-definition=lean4.xml",
            "--mathjax=https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js",
            "--bibliography=bib.json",
            "--citeproc",
            "-o",
            str(html),
            str(md),
        ]
    )

    # Post-processing
    # ---------------

    # Remove the default inline style generated by pandoc
    with html.open("rb") as f:
        tree = etree.parse(f, etree.HTMLParser())

    root = tree.getroot()
    head = root.find(".//head")
    style = head.find("style")  # first <style> only
    if style is not None:
        head.remove(style)

    # Enable anchors
    head.append(
        etree.fromstring("""
          <script type="module">
            import 'https://cdn.jsdelivr.net/npm/anchor-js/anchor.min.js';
            anchors.add("h1, h2, h3");
          </script>
        """)
    )

    # Write the modified HTML document
    tree.write(html, method="html", encoding="utf-8")


if __name__ == "__main__":
    build("Chapter12.lean")
