#!/bin/env bash

set -euo pipefail

mol Chapter12.lean # -> Chapter12.lean.md
pandoc -s --metadata title="LoVe – Chapter 12" \
  --no-highlight \
  --mathjax=https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js \
  -o Chapter12.lean.html \
  Chapter12.lean.md

# TODO: get rid of this monstruosity, use Python
# Test some Pandoc CSS erasure to get a proper shiki highlighting.
# *Maybe* eschew --standalone option and assemble myself?

awk '/<\/body>/{
  print "<script type=\"module\">"
  print "  import { codeToHtml } from \"https://esm.sh/shiki@3\";"
  print "  for (const block of document.querySelectorAll(\"pre[class] > code\")) {"
  print "    const lang = block.className.match(/language-(\\w+)/)?.[1] ?? \"text\";"
  print "    const parent = block.parentElement;"
  print "    parent.outerHTML = await codeToHtml(block.textContent, { lang, theme: \"github-dark\" });"
  print "  }"
  print "</script>"
}
{ print }' Chapter12.lean.html > tmp && mv tmp Chapter12.lean.html