[workspace]
authors = ["Sébastien Boisgérault <Sebastien.Boisgerault@gmail.com>"]
channels = ["conda-forge"]
name = "leap"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pandoc = ">=3.7.0.2,<4"
