import Mathlib

open Filter   -- convenience
open Topology -- needed for the neighbourhood fancy syntax

/-!
- Translate from abstract tendsto def limits to the usual δ-ε
  statements when considering functions ℝ → ℝ.
  WARNING: consider punctured neighbourhoods in the def!
  TODO: look at 𝓝[≠] x aka nhdsWithin x {x}ᶜ
-/

/-!
Note: `𝓝[≠] x` (type antislash + nhds for the `𝓝`)
is a notation for `nhdsWithin x {x}ᶜ`
Note: we need to open Topology to make it work!
-/

-- Syntactic sugar for `Filter.Tendsto f (nhdsWithin x {x}ᶜ) (nhds ℓ)`

def limAt (f : ℝ → ℝ) (x ℓ : ℝ) := Filter.Tendsto f (𝓝[≠] x) (𝓝 ℓ)


#print nhdsWithin
-- def nhdsWithin.{u_1} : {X : Type u_1} → [TopologicalSpace X] → X → Set X → Filter X :=
-- fun {X} [TopologicalSpace X] x s => nhds x ⊓ Filter.principal s

#check Filter.mem_principal
-- Filter.mem_principal.{u_1} {α : Type u_1} {s t : Set α} :
--     s ∈ Filter.principal t ↔ t ⊆ s

/-!
Mmm, yummy! 😋 Afaict, the meet ⊓ or nhds x and Filter.principal s
is the filter generated by the intersections r ∩ t, where r is in nhds x
and t is in Filter.principal s. So, a set v is a punctured neighbourhood
of x iff it contains the intersection of a neighbourhood of x and
either the full space or the full space minus x, so iff
it is either a neighbourghood of x minus x or the neighbourhood of x
itself. Yeah, ok, that checks out.
-/

#check mem_nhdsWithin
-- mem_nhdsWithin.{u_1} {α : Type u_1} [TopologicalSpace α]
--     {t : Set α} {a : α} {s : Set α} :
--     t ∈ 𝓝[s] a ↔ ∃ u, IsOpen u ∧ a ∈ u ∧ u ∩ s ⊆ t

#check Metric.tendsto_nhdsWithin_nhds
-- Metric.tendsto_nhdsWithin_nhds.{u, v} {α : Type u} {β : Type v}
--     [PseudoMetricSpace α] {s : Set α} [PseudoMetricSpace β]
--     {f : α → β} {a : α} {b : β} :
--     Filter.Tendsto f (𝓝[s] a) (𝓝 b) ↔
--     ∀ ε > 0, ∃ δ > 0, ∀ ⦃x : α⦄, x ∈ s → dist x a < δ → dist (f x) b < ε


theorem limAt_eq (f : ℝ → ℝ) (x ℓ : ℝ) :
    Filter.Tendsto f (𝓝[≠] x) (𝓝 ℓ) ↔
    (
      ∀ ε > 0, ∃ δ > 0, ∀ ⦃y : ℝ⦄, y ≠ x →
      |y - x| < δ → |f y - ℓ| < ε
    ) := by
  simp only [
    Metric.tendsto_nhdsWithin_nhds,
    Real.dist_eq,
    Set.mem_compl_singleton_iff
  ]


/-!
- Show that lim when x -> 1 of (x^2 - 1) / (x - 1) = 1
-/

namespace Ex0

noncomputable def f (x : ℝ) := (x^2 - 1) / (x - 1)

lemma f_eq (x : ℝ) (x_ne_1 : x ≠ 1) : f x = x + 1 := by
  rw [f]
  grind

theorem lim_f_one : Tendsto f (𝓝[≠] 1) (𝓝 2) := by
  rw [limAt_eq]
  intro ε ε_pos
  use ε
  constructor
  exact ε_pos
  intro y y_ne_one
  simp only [f_eq y y_ne_one]
  ring_nf
  simp only [imp_self]

end Ex0



/-!
- Prove that x ↦ x^2 - 1 is continous at x = 2
-/

#print ContinuousAt
-- def ContinuousAt.{u_1, u_2} : {X : Type u_1} → {Y : Type u_2} →
--     [TopologicalSpace X] → [TopologicalSpace Y] → (X → Y) → X → Prop :=
--   fun {X} {Y} [TopologicalSpace X] [TopologicalSpace Y] f x =>
--   Tendsto f (𝓝 x) (𝓝 (f x))

namespace Ex1

def f (x : ℝ) := x^2 - 1

lemma f_continousAt_two_delta_eps (ε : ℝ) (ε_pos : ε > 0) :
    ∃ δ > 0, ∀ x, |x - 2| < δ → |f x - f 2| < ε := by
  let δ := min 1 (ε / 5)
  have δ_pos : 0 < δ := by grind
  have δ_le_one : δ ≤ 1 := by grind
  have δ_le_ε_div_five : δ ≤ ε / 5 := by grind
  use δ
  constructor; positivity
  intro x hx
  simp only [f]
  ring_nf at *

  have bound_1 : |-4 + x^2| < δ * (δ + 4) := by
    calc |-4 + x^2|
      _ = |(x - 2) * (x + 2)| := by ring_nf
      _ = |x - 2| * |x + 2| := by apply abs_mul
      _ = |x - 2| * |x - 2 + 4| := by ring_nf
      _ ≤ |x - 2| * (|x - 2| + |4|) := by
        apply mul_le_mul
        rfl
        apply abs_add_le
        repeat apply abs_nonneg
      _ ≤ |x - 2| * (|x - 2| + 4) := by norm_num
      _ < δ * (δ + 4) := by admit

  have bound_2 : δ * (δ + 4) ≤ ε := by
    calc δ * (δ + 4)
      _ ≤ (ε / 5) * (1 + 4) := by apply mul_le_mul <;> linarith
      _ = ε := by grind

  exact lt_of_lt_of_le bound_1 bound_2

theorem f_continousAt_two : ContinuousAt f 2 := by
  rw [ContinuousAt]
  simp only [Metric.tendsto_nhds, Real.dist_eq]
  -- ⊢ ∀ ε > 0, ∀ᶠ (x : ℝ) in 𝓝 2, |f x - f 2| < ε
  simp only [Filter.Eventually]
  simp only [mem_nhds_iff_exists_Ioo_subset]
  -- ∀ ε > 0, ∃ l u, 2 ∈ Set.Ioo l u ∧ Set.Ioo l u ⊆ {x | |f x - f 2| < ε}
  intro ε ε_pos
  have ⟨δ, δ_pos, hδ⟩ := f_continousAt_two_delta_eps ε ε_pos
  use (2 - δ), (2 + δ)
  constructor
  grind
  intro x
  specialize hδ x
  simp only [Set.mem_Ioo]
  intro h
  simp only [Set.mem_setOf]
  exact hδ (show |x - 2| < δ from by grind)

end Ex1


/-!
- Prove that the sum of continuous functions at x is continuous at x
-/

namespace Ex2

example (f g : ℝ → ℝ) (x : ℝ) :
    ContinuousAt f x → ContinuousAt g x → ContinuousAt (f + g) x := by
  intro continuousAt_f_x continuousAt_g_x
  simp only [
    ContinuousAt,
    Metric.tendsto_nhds,
    Real.dist_eq,
    Filter.Eventually,
    mem_nhds_iff_exists_Ioo_subset
  ] at *
  simp only [Pi.add_apply]
  intro ε ε_pos
  specialize continuousAt_f_x (ε / 2) (by positivity)
  specialize continuousAt_g_x (ε / 2) (by positivity)
  have ⟨l₁, u₁, h₁, k₁⟩ := continuousAt_f_x; clear continuousAt_f_x
  have ⟨l₂, u₂, h₂, k₂⟩ := continuousAt_g_x; clear continuousAt_g_x
  let l := max l₁ l₂
  let u := min u₁ u₂
  use l, u
  simp only [Set.mem_Ioo] at *
  constructor
  . grind
  . intro y y_in_Ioo_l_u
    simp only [Set.mem_Ioo] at *
    have y_in_ioo₁ : y ∈ Set.Ioo l₁ u₁ := by grind
    have y_in_ioo₂ : y ∈ Set.Ioo l₂ u₂ := by grind
    specialize k₁ y_in_ioo₁
    specialize k₂ y_in_ioo₂
    simp only [Set.mem_setOf] at *
    grind

end Ex2

/-!
- Prove the sequential criteron for limits of functions.
-/

namespace Ex3

example (f : ℝ → ℝ) (x ℓ : ℝ) :
  (
    ∀ (a : ℕ → ℝ),
    (∀ n, a n ≠ x) →
    (Tendsto a atTop (𝓝 x)) →
    Tendsto (f ∘ a) atTop (𝓝 ℓ)
  ) →
  Tendsto f (𝓝[≠] x) (𝓝 ℓ) := by
  intro sequential_limit
  simp only [
    Metric.tendsto_nhdsWithin_nhds,
    Metric.tendsto_atTop,
    Real.dist_eq,
    Set.mem_compl_singleton_iff,
  ] at *
  intro ε ε_pos
  by_contra h -- 💡 Eureka!
  push_neg at h
  let a (n : ℕ) : ℝ := h (1 / 2^n) (by positivity) |>.choose
  specialize sequential_limit a
  -- simp only [a] at sequential_limit
  specialize sequential_limit (
    fun n => (h (1 / 2^n) (by positivity)) |>.choose_spec.1
  )
  specialize sequential_limit (by admit) -- **TODO**

  admit

end Ex3
