import Mathlib

open Filter   -- convenience
open Topology -- needed for the neighbourhood fancy syntax

/-!
- Translate from abstract tendsto def limits to the usual δ-ε
  statements when considering functions ℝ → ℝ.
  WARNING: consider punctured neighbourhoods in the def!
  TODO: look at 𝓝[≠] x aka nhdsWithin x {x}ᶜ
-/

/-!
Note: `𝓝[≠] x` (type antislash + nhds for the `𝓝`)
is a notation for `nhdsWithin x {x}ᶜ`
Note: we need to open Topology to make it work!
-/

-- Syntactic sugar for `Filter.Tendsto f (nhdsWithin x {x}ᶜ) (nhds ℓ)`

def limAt (f : ℝ → ℝ) (x ℓ : ℝ) := Filter.Tendsto f (𝓝[≠] x) (𝓝 ℓ)


#print nhdsWithin
-- def nhdsWithin.{u_1} : {X : Type u_1} → [TopologicalSpace X] → X → Set X → Filter X :=
-- fun {X} [TopologicalSpace X] x s => nhds x ⊓ Filter.principal s

#check Filter.mem_principal
-- Filter.mem_principal.{u_1} {α : Type u_1} {s t : Set α} :
--     s ∈ Filter.principal t ↔ t ⊆ s

/-!
Mmm, yummy! 😋 Afaict, the meet ⊓ or nhds x and Filter.principal s
is the filter generated by the intersections r ∩ t, where r is in nhds x
and t is in Filter.principal s. So, a set v is a punctured neighbourhood
of x iff it contains the intersection of a neighbourhood of x and
either the full space or the full space minus x, so iff
it is either a neighbourghood of x minus x or the neighbourhood of x
itself. Yeah, ok, that checks out.
-/

#check mem_nhdsWithin
-- mem_nhdsWithin.{u_1} {α : Type u_1} [TopologicalSpace α]
--     {t : Set α} {a : α} {s : Set α} :
--     t ∈ 𝓝[s] a ↔ ∃ u, IsOpen u ∧ a ∈ u ∧ u ∩ s ⊆ t

#check Metric.tendsto_nhdsWithin_nhds
-- Metric.tendsto_nhdsWithin_nhds.{u, v} {α : Type u} {β : Type v}
--     [PseudoMetricSpace α] {s : Set α} [PseudoMetricSpace β]
--     {f : α → β} {a : α} {b : β} :
--     Filter.Tendsto f (𝓝[s] a) (𝓝 b) ↔
--     ∀ ε > 0, ∃ δ > 0, ∀ ⦃x : α⦄, x ∈ s → dist x a < δ → dist (f x) b < ε


theorem limAt_eq (f : ℝ → ℝ) (x ℓ : ℝ) :
    Filter.Tendsto f (𝓝[≠] x) (𝓝 ℓ) ↔
    (
      ∀ ε > 0, ∃ δ > 0, ∀ ⦃y : ℝ⦄, y ≠ x →
      |y - x| < δ → |f y - ℓ| < ε
    ) := by
  simp only [
    Metric.tendsto_nhdsWithin_nhds,
    Real.dist_eq,
    Set.mem_compl_singleton_iff
  ]


/-!
- Show that lim when x -> 1 of (x^2 - 1) / (x - 1) = 1
-/

namespace Ex0

noncomputable def f (x : ℝ) := (x^2 - 1) / (x - 1)

lemma f_eq (x : ℝ) (x_ne_1 : x ≠ 1) : f x = x + 1 := by
  rw [f]
  grind

theorem lim_f_one : Tendsto f (𝓝[≠] 1) (𝓝 2) := by
  rw [limAt_eq]
  intro ε ε_pos
  use ε
  constructor
  exact ε_pos
  intro y y_ne_one
  simp only [f_eq y y_ne_one]
  ring_nf
  simp only [imp_self]

end Ex0



/-!
- Prove that x ↦ x^2 - 1 is continous at x = 2
-/

#print ContinuousAt
-- def ContinuousAt.{u_1, u_2} : {X : Type u_1} → {Y : Type u_2} →
--     [TopologicalSpace X] → [TopologicalSpace Y] → (X → Y) → X → Prop :=
--   fun {X} {Y} [TopologicalSpace X] [TopologicalSpace Y] f x =>
--   Tendsto f (𝓝 x) (𝓝 (f x))

namespace Ex1

def f (x : ℝ) := x^2 - 1

lemma f_continousAt_two_delta_eps (ε : ℝ) (ε_pos : ε > 0) :
    ∃ δ > 0, ∀ x, |x - 2| < δ → |f x - f 2| < ε := by
  let δ := min 1 (ε / 8)
  use δ
  constructor; positivity
  intro x hx
  simp only [f]
  ring_nf at *
  simp only [show -4 + x^2 = (-2 + x) * (2 + x) from by ring_nf]
  simp only [abs_mul]
  -- ε : ℝ
  -- ε_pos : ε > 0
  -- δ : ℝ := min 1 (ε / 8)
  -- x : ℝ
  -- hx : |-2 + x| < δ
  -- ⊢ |-2 + x| * |2 + x| < ε
  admit

theorem f_continousAt_two : ContinuousAt f 2 := by
  rw [ContinuousAt]
  simp only [Metric.tendsto_nhds, Real.dist_eq]
  -- ⊢ ∀ ε > 0, ∀ᶠ (x : ℝ) in 𝓝 2, |f x - f 2| < ε
  simp only [Filter.Eventually]
  simp only [mem_nhds_iff_exists_Ioo_subset]
  -- ∀ ε > 0, ∃ l u, 2 ∈ Set.Ioo l u ∧ Set.Ioo l u ⊆ {x | |f x - f 2| < ε}
  intro ε ε_pos
  have ⟨δ, δ_pos, hδ⟩ := f_continousAt_two_delta_eps ε ε_pos
  use (2 - δ), (2 + δ)
  constructor
  grind
  intro x
  specialize hδ x
  simp only [Set.mem_Ioo]
  intro h
  simp only [Set.mem_setOf]
  exact hδ (show |x - 2| < δ from by grind)

end Ex1


/-!
- Relate those limits with ContinousAt statements.

- Prove that the sum of continuous functions at x is continuous at x

- Prove the sequential criteron for limits of functions.

-/
