import Mathlib

open Topology -- needed for the neighbourhood fancy syntax

/-!
- Translate from abstract tendsto def limits to the usual δ-ε
  statements when considering functions ℝ → ℝ.
  WARNING: consider punctured neighbourhoods in the def!
  TODO: look at 𝓝[≠] x aka nhdsWithin x {x}ᶜ
-/

/-!
Note: `𝓝[≠] x` (type antislash + nhds for the `𝓝`)
is a notation for `nhdsWithin x {x}ᶜ`
Note: we need to open Topology to make it work!
-/

-- Syntactic sugar for `Filter.Tendsto f (nhdsWithin x {x}ᶜ) (nhds ℓ)`

def limAt (f : ℝ → ℝ) (x ℓ : ℝ) := Filter.Tendsto f (𝓝[≠] x) (𝓝 ℓ)


#print nhdsWithin
-- def nhdsWithin.{u_1} : {X : Type u_1} → [TopologicalSpace X] → X → Set X → Filter X :=
-- fun {X} [TopologicalSpace X] x s => nhds x ⊓ Filter.principal s

#check Filter.mem_principal
-- Filter.mem_principal.{u_1} {α : Type u_1} {s t : Set α} :
--     s ∈ Filter.principal t ↔ t ⊆ s

/-!
Mmm, yummy! 😋 Afaict, the meet ⊓ or nhds x and Filter.principal s
is the filter generated by the intersections r ∩ t, where r is in nhds x
and t is in Filter.principal s. So, a set v is a punctured neighbourhood
of x iff it contains the intersection of a neighbourhood of x and
either the full space or the full space minus x, so iff
it is either a neighbourghood of x minus x or the neighbourhood of x
itself. Yeah, ok, that checks out.
-/

#check mem_nhdsWithin
-- mem_nhdsWithin.{u_1} {α : Type u_1} [TopologicalSpace α]
--     {t : Set α} {a : α} {s : Set α} :
--     t ∈ 𝓝[s] a ↔ ∃ u, IsOpen u ∧ a ∈ u ∧ u ∩ s ⊆ t

#check Metric.tendsto_nhdsWithin_nhds
-- Metric.tendsto_nhdsWithin_nhds.{u, v} {α : Type u} {β : Type v}
--     [PseudoMetricSpace α] {s : Set α} [PseudoMetricSpace β]
--     {f : α → β} {a : α} {b : β} :
--     Filter.Tendsto f (𝓝[s] a) (𝓝 b) ↔
--     ∀ ε > 0, ∃ δ > 0, ∀ ⦃x : α⦄, x ∈ s → dist x a < δ → dist (f x) b < ε


theorem limAt_eq (f : ℝ → ℝ) (x ℓ : ℝ) :
    Filter.Tendsto f (𝓝[≠] x) (𝓝 ℓ) ↔
    (
      ∀ ε > 0, ∃ δ > 0, ∀ ⦃y : ℝ⦄, y ∈ ({x}ᶜ : Set ℝ) →
      |y - x| < δ → |f y - ℓ| < ε
    ) := by
  simp only [Metric.tendsto_nhdsWithin_nhds, Real.dist_eq]



/-!
- Show that lim when x -> 1 of (x^2 - 1) / (x - 1) = 1

- δ-ε def of continuity at.

- Prove that x ↦ x^2 - 1 is continous at x = 2

- Relate those limits with ContinousAt statements.

- Prove that the sum of continuous functions at x is continuous at x

- Prove the sequential criteron for limits of functions.

-/
